const S={token:'coc-token',player:'coc-last-player-tag',clan:'coc-last-clan-tag',war:'coc-last-war-tag',location:'coc-last-location'};
const API='https://api.clashofclans.com/v1';
const $=id=>document.getElementById(id);
const el={tokenInput:$('tokenInput'),tokenStatus:$('tokenStatus'),msg:$('globalMessage'),playerTag:$('playerTagInput'),clanTag:$('clanTagInput'),warTag:$('warClanTagInput'),location:$('locationSelect'),playerSummary:$('playerSummary'),playerDetails:$('playerDetails'),clanSummary:$('clanSummary'),clanMembers:$('clanMembers'),warSummary:$('warSummary'),warRoster:$('warRoster'),playerRankings:$('playerRankings'),clanRankings:$('clanRankings'),playerJson:$('playerJson'),clanJson:$('clanJson'),membersJson:$('membersJson'),warJson:$('warJson'),leagueJson:$('leagueGroupJson'),locationsJson:$('locationsJson'),playerRankingsJson:$('playerRankingsJson'),clanRankingsJson:$('clanRankingsJson')};
const getToken=()=>localStorage.getItem(S.token)?.trim()||'';
const setPill=ok=>{el.tokenStatus.className=`pill ${ok?'success':'neutral'}`;el.tokenStatus.textContent=ok?'Token gespeichert':'Kein Token gespeichert';};
const show=(text,t='success')=>{el.msg.textContent=text;el.msg.className=`message ${t}`;}; const hide=()=>{el.msg.className='message hidden';el.msg.textContent='';};
const norm=raw=>{const c=(raw||'').trim().replace(/\s+/g,'').toUpperCase().replace(/^%23/,'#').replace(/^#+/,'#'); return c ? (c.startsWith('#')?c:'#'+c) : '';};
const enc=tag=>encodeURIComponent(norm(tag)); const num=v=>v===null||v===undefined||v===''?'–':new Intl.NumberFormat('de-DE').format(v); const date=v=>v&&v.length>=8?`${v.slice(6,8)}.${v.slice(4,6)}.${v.slice(0,4)}`:'–';
const json=(target,data)=>target.textContent=JSON.stringify(data??{},null,2);
function metrics(target,items){target.classList.remove('empty');target.innerHTML=items.map(i=>`<article class="metric"><span class="metric-label">${i.label}</span><strong>${i.value}</strong></article>`).join('');}
function listCard(title,items){return `<section class="card"><h4>${title}</h4><ul>${(items.length?items:['Keine Daten']).map(i=>`<li>${i}</li>`).join('')}</ul></section>`;}
function needToken(){const t=getToken(); if(!t) throw new Error('Bitte zuerst einen Clash of Clans API Token speichern.'); return t;}
async function api(path){const token=needToken(); const res=await fetch(`${API}${path}`,{headers:{Accept:'application/json',Authorization:`Bearer ${token}`}}); let data=null; try{data=await res.json();}catch{} if(!res.ok) throw new Error(data?.reason||data?.message||`HTTP ${res.status}`); return data;}
function activate(id){document.querySelectorAll('.content').forEach(p=>p.classList.toggle('active',p.id===id)); document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.target===id));}
async function loadPlayer(tag){const n=norm(tag); if(!n) throw new Error('Bitte ein Spieler-Tag eingeben.'); localStorage.setItem(S.player,n); const p=await api(`/players/${enc(n)}`); metrics(el.playerSummary,[{label:'Name',value:p.name||'–'},{label:'Tag',value:p.tag||n},{label:'Town Hall',value:num(p.townHallLevel)},{label:'Trophäen',value:num(p.trophies)},{label:'Bestmarke',value:num(p.bestTrophies)},{label:'XP Level',value:num(p.expLevel)},{label:'Angriffe gewonnen',value:num(p.attackWins)},{label:'Verteidigungen gewonnen',value:num(p.defenseWins)}]); el.playerDetails.innerHTML=`<div class="info">${listCard('Helden',(p.heroes||[]).map(x=>`${x.name}: Level ${x.level}`))}${listCard('Truppen',(p.troops||[]).slice(0,12).map(x=>`${x.name}: Level ${x.level}`))}${listCard('Zauber',(p.spells||[]).map(x=>`${x.name}: Level ${x.level}`))}${listCard('Erfolge',(p.achievements||[]).slice(0,8).map(x=>`${x.name}: ${num(x.value)}`))}</div>`; json(el.playerJson,p); show(`Spielerdaten für ${p.name||n} geladen.`);}
function membersTable(items){if(!items?.length){el.clanMembers.innerHTML='<div class="empty">Keine Mitglieder gefunden.</div>'; return;} el.clanMembers.innerHTML=`<div class="table"><div class="thead"><span>Rang</span><span>Name</span><span>Rolle</span><span>Trophäen</span><span>Spenden</span></div>${items.slice(0,20).map(m=>`<div class="tr"><span><span class="badge">#${m.clanRank??'–'}</span></span><span>${m.name}</span><span>${m.role||'–'}</span><span>${num(m.trophies)}</span><span>${num(m.donations)}</span></div>`).join('')}</div>`;}
async function loadClan(tag){const n=norm(tag); if(!n) throw new Error('Bitte ein Clan-Tag eingeben.'); localStorage.setItem(S.clan,n); const [c,m]=await Promise.all([api(`/clans/${enc(n)}`),api(`/clans/${enc(n)}/members`)]); metrics(el.clanSummary,[{label:'Clanname',value:c.name||'–'},{label:'Tag',value:c.tag||n},{label:'Level',value:num(c.clanLevel)},{label:'Mitglieder',value:num(c.members)},{label:'Clan Punkte',value:num(c.clanPoints)},{label:'War Wins',value:num(c.warWins)},{label:'Win Streak',value:num(c.warWinStreak)},{label:'Capital League',value:c.capitalLeague?.name||'–'}]); membersTable(m.items||[]); json(el.clanJson,c); json(el.membersJson,m.items||[]); show(`Claninfos für ${c.name||n} geladen.`);}
function warSides(w){const side=(title,members=[])=>`<section class="sub"><h4>${title}</h4><div class="ranking-list">${members.slice(0,15).map(m=>`<article class="ranking"><div class="badge">#${m.mapPosition||'–'}</div><div class="ranking-name"><strong>${m.name}</strong><span>Angriffe: ${num(m.attacks?.length||0)}</span></div><div class="ranking-value">${num(m.stars||0)}★</div></article>`).join('')}</div></section>`; el.warRoster.innerHTML=`<div class="dual">${side(w.clan?.name||'Eigenes Clanlager',w.clan?.members||[])}${side(w.opponent?.name||'Gegner',w.opponent?.members||[])}</div>`;}
async function loadWar(tag){const n=norm(tag); if(!n) throw new Error('Bitte ein Clan-Tag eingeben.'); localStorage.setItem(S.war,n); const war=await api(`/clans/${enc(n)}/currentwar`); let lg={info:'Keine CWL Gruppeninfos verfügbar oder Clan aktuell nicht in Liga.'}; try{lg=await api(`/clans/${enc(n)}/currentwar/leaguegroup`);}catch{} metrics(el.warSummary,[{label:'Status',value:war.state||'–'},{label:'Team Size',value:num(war.teamSize)},{label:'Clan Sterne',value:num(war.clan?.stars||0)},{label:'Gegner Sterne',value:num(war.opponent?.stars||0)},{label:'Clan Zerstörung',value:`${war.clan?.destructionPercentage??'–'}%`},{label:'Gegner Zerstörung',value:`${war.opponent?.destructionPercentage??'–'}%`},{label:'Start',value:date(war.startTime||'')},{label:'Ende',value:date(war.endTime||'')}]); warSides(war); json(el.warJson,war); json(el.leagueJson,lg); show(`Kriegsdaten für ${war.clan?.name||n} geladen.`);}
function rankingList(target,items,type){target.classList.remove('empty'); if(!items?.length){target.innerHTML='<div class="empty">Keine Daten gefunden.</div>'; return;} target.className='ranking-list'; target.innerHTML=items.slice(0,15).map(i=>`<article class="ranking"><div class="badge">#${i.rank}</div><div class="ranking-name"><strong>${i.name}</strong><span>${type==='player'?(i.tag||'–'):`${num(i.members)} Mitglieder`}</span></div><div class="ranking-value">${num(type==='player'?i.trophies:i.clanPoints)}</div></article>`).join('');}
async function loadLocations(){const l=await api('/locations'); const items=l.items||[]; el.location.innerHTML=items.map(x=>`<option value="${x.id}">${x.name}</option>`).join(''); const saved=localStorage.getItem(S.location); if(saved&&items.some(x=>String(x.id)===saved)) el.location.value=saved; json(el.locationsJson,items);}
async function loadRankings(){const id=el.location.value; if(!id) throw new Error('Kein Standort ausgewählt.'); localStorage.setItem(S.location,id); const [p,c]=await Promise.all([api(`/locations/${id}/rankings/players`),api(`/locations/${id}/rankings/clans`)]); rankingList(el.playerRankings,p.items||[],'player'); rankingList(el.clanRankings,c.items||[],'clan'); json(el.playerRankingsJson,p.items||[]); json(el.clanRankingsJson,c.items||[]); show('Rankings geladen.');}
function boot(){el.tokenInput.value=getToken(); el.playerTag.value=localStorage.getItem(S.player)||''; el.clanTag.value=localStorage.getItem(S.clan)||''; el.warTag.value=localStorage.getItem(S.war)||''; setPill(!!getToken());}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>activate(b.dataset.target))); $('toggleTokenBtn').addEventListener('click',()=>{el.tokenInput.type=el.tokenInput.type==='password'?'text':'password';}); $('saveTokenBtn').addEventListener('click',()=>{const v=el.tokenInput.value.trim(); if(!v){show('Bitte zuerst einen Token einfügen.','error'); return;} localStorage.setItem(S.token,v); setPill(true); show('Token gespeichert.');}); $('clearTokenBtn').addEventListener('click',()=>{localStorage.removeItem(S.token); el.tokenInput.value=''; setPill(false); show('Token entfernt.');}); $('playerForm').addEventListener('submit',async e=>{e.preventDefault(); hide(); try{await loadPlayer(el.playerTag.value);}catch(err){show(err.message,'error');}}); $('clanForm').addEventListener('submit',async e=>{e.preventDefault(); hide(); try{await loadClan(el.clanTag.value);}catch(err){show(err.message,'error');}}); $('warForm').addEventListener('submit',async e=>{e.preventDefault(); hide(); try{await loadWar(el.warTag.value);}catch(err){show(err.message,'error');}}); $('loadRankingsBtn').addEventListener('click',async()=>{hide(); try{await loadRankings();}catch(err){show(err.message,'error');}});}
(async function init(){boot(); bind(); if(getToken()){try{await loadLocations(); show('Standorte geladen. Du kannst direkt loslegen.');}catch(err){show(`Start fehlgeschlagen: ${err.message}`,'error');}}})();
